### ISSUE TITLE
Missing summary decay

### ISSUE THREAD

**Issue by grobie** [prometheus/client_ruby#12]
There is currently no decay of summary observations. This might lead to wrong quantile metrics in low throughput values due to stale values skewing results.

**Comment by Reifier** [comment]
2015? I guess nobody uses prometheus ruby client.

**Comment by dmagliola** [comment]
Hi @reifier. There has indeed been low activity on this repo, but for the last two months, we've been picking these up. There'll be a 1.0 version to fix what has been the main issue for quite a long time now (multi-process support), and we're starting to go through old issues and PRs and work through the gradually.

If you are using prometheus and ruby, we encourage you to try out latest release candidate, or keep an eye out for our soon to come 1.0

**Comment by dmagliola** [comment]
As for this issue... We no longer support quantiles on Summaries, because we prioritised multiprocess support, and the way quantiles were stored did not work with our new storage system.

We took the direction of the Python client, and changed Summaries to support only count and sum.

This may change in the future, but for the time being, I'll close this issue.
