### ISSUE TITLE
Drop Rack::Deflater line in README.md ?

### ISSUE THREAD

**Issue by JonJagger** [prometheus/client_ruby#193]
README.md has this code fragment for config.ru:
```
require 'rack'
require 'prometheus/middleware/collector'
require 'prometheus/middleware/exporter'

use Rack::Deflater
use Prometheus::Middleware::Collector
use Prometheus::Middleware::Exporter

run ->(_) { [200, {'Content-Type' => 'text/html'}, ['OK']] }
```

I put the `use Rack::Deflater` line into my `config.ru` and it broke the CSS being returned by my Sinatra server (via an nginx service). Unfortunately, as it stands, it looks like you can't just add the given code example as middleware to a Sinatra server. Maybe worth mentioning?

**Comment by dmagliola** [comment]
Hi Jon, I'm sorry for my late response...
Do you have more detail as to how `Deflater` broke your CSS? I'm just really surprised by that, since all it should do is `gzip` the response...

I agree with you that we don't need that at all and it has nothing to do with Prometheus, and while I'd recommend having it, that's true of *any* app, nothing to do with Prometheus itself. 
Any chance you can open a PR removing all mentions of it from our docs?

Thanks!

**Comment by lawrencejones** [comment]
As a quick drive-by, I thought the Prometheus community officially encourages gzip'ing collector responses. It seems fair to include this in the examples if it's something we actively push, as a large percent of people will expect example code to be considered best practice.

**Comment by JonJagger** [comment]
Hi Daniel, I remember I was indeed very surprised! The broken CSS went live for a short while; my site 'worked' but looked crazy! I removed `Deflater` with this commit https://github.com/cyber-dojo/custom-chooser/commit/c4518286b8ee73d3835dcf6352b36008c51303f9 and then the CSS was back. I'm sorry I don't have any more info and have a lot on at present. Cheers

**Comment by dmagliola** [comment]
Fair point @lawrence, I agree.
I'm closing this issue then
