### ISSUE TITLE
Collector Middleware: Make variable path segments configurable

### ISSUE THREAD

**Issue by friegger** [prometheus/client_ruby#198]
When using the Collector middleware it currently generically replaces only path segments [that match](https://github.com/prometheus/client_ruby/blob/872a8ebc1a832af907a84674c486bf98af6ffa92/lib/prometheus/middleware/collector.rb#L90) an id or an uuid.

My understanding is that in general it is desirable to have all variable path segments replaced, otherwise this would create a lot of series. Each series would not be as useful. Is this correct? If so, the Collector middleware is not very useful for most applications.

Now, which path segment is variable and which is not of course depends on the application. One could just collect the metrics with their own custom collector implementation and only use the Extractor middleware. Alternatively, the Collector middleware could be made configurable in such a way that the patterns to be replaced can be provided from the outside.

What's your take on this?

Context: https://github.com/cloudfoundry/bosh/issues/2271

**Comment by dmagliola** [comment]
Hi @friegger,

Our take on this is that attempting to make the Collector flexible enough to handle all different cases makes it extremely convoluted and ends up still not catering for everyone (we tried this and we felt it didn't go well at all).

Instead, we went with the approach of providing an "example" Collector, that showcases how you'd declare and increment these metrics in a Rack application, and encourage people to make their own / modify the example as they need to fit their use case: https://github.com/prometheus/client_ruby/blob/master/examples/rack/README.md#collector

We think this is better than having a more configurable Collector, because as you said, the needs will depend highly on the application.

**Comment by friegger** [comment]
Sorry, I missed that part of the documentation. It perfectly answers my question.
