### ISSUE TITLE
How to metrify ActiveRecord sql queries and Redis jobs (sidekiq/resque)?

### ISSUE THREAD

**Issue by pedrofurtado** [prometheus/client_ruby#274]
How to metrify ActiveRecord sql queries and Redis jobs (sidekiq/resque), and turn all this available in /metrics endpoint?

**Comment by Sinjo** [comment]
Hi @pedrofurtado,

Those aren't integrations we provide in this gem, as our focus is on building a Prometheus client rather than a wide range of framework integrations. We think those integrations are better served by separate gems.

I can't vouch for either of these as I've not used them, but you may find [this blog post on instrumenting queries](https://firehydrant.com/blog/instrumenting-ruby-on-rails-with-prometheus/) and [this Sidekiq integration written by Fastly](https://github.com/fastly/sidekiq-prometheus) useful.

I'm going to close this issue as there's no work for us to do, but I hope you find what you're looking for!
