### ISSUE TITLE
Add Child notion to client

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/client_ruby#35]
Currently labels are handled by being the first argument to all functions. This gives the incorrect impression that all metrics should labels (in reality most metrics don't have labels) and makes label-less use harder.

This client should follow the structure laid out in https://prometheus.io/docs/instrumenting/writing_clientlibs/#labels

In addition the user should be required to specify all their label names at metric creation time.

**Comment by grobie** [comment]
Label-less use does not get harder by having an optional labels parameter. See the first example from the readme. This is a common ruby pattern.

```ruby
http_requests = prometheus.counter(:http_requests, 'A counter of HTTP requests made')

# start using the counter
http_requests.increment
```

Using a labels() method and calling metric functions on that will help performance-wise though. I added this to milestone v0.7.0.

**Comment by brian-brazil** [comment]
> Label-less use does not get harder by having an optional labels parameter. 

The labels parameter is first, so if you want a non-default value it makes it harder.

**Comment by dmagliola** [comment]
@brian-brazil this is now covered as part of the changes we made in PR #95. We require labels at creation time, they're no longer the first parameter, and the Child notion is implemented through the `with_labels` methods.

I'm going to close this issue due to this but feel free to reopen if you think there's still work to do on this.
