### ISSUE TITLE
Metrics without `path`

### ISSUE THREAD

**Issue by gaynetdinov** [prometheus/client_ruby#50]
Hello. 

I'm using current master and trying to get rid of the `path` parameter in the metrics. 

If I do this
```ruby
use Prometheus::Middleware::Collector, counter_label_builder: ->(env, code) {
  {
    method: env['REQUEST_METHOD'].downcase,
    code: code
  }
}
```
then `http_server_request_duration_seconds_bucket` metric gets `path` parameter and graph which shows percentiles becomes suuuuper slow. However with such setup `http_server_requests_total` metric doesn't have `path`, so graph which shows request per seconds works ok.

If I change to `duration_label_builder`, then it works vice versa: `http_server_requests_total` gets `path` and `http_server_request_duration_seconds_bucket` does not have it. 

I'm confused how to remove `path` from both metrics, because having `path` in any of these metrics leads to super slow graphs. As I understand having `path` in metrics makes in slow to squash all these metrics with different `path` when you group by something like `method`, for example for requests-per-second graphs I have the following query: 

`sum(rate(http_server_request_duration_seconds_count{job="myjob"}[1m])) by(method)`

And if there are each `http_server_request_duration_seconds_count ` per `path`, it becomes slow. 

Thanks.

**Comment by grobie** [comment]
You'll need to change both label builders if you want to remove path from
all metrics. E.g.

```ruby
use Prometheus::Middleware::Collector,
  counter_label_builder: ->(env, code) { ... },
  duration_label_builder: ->(env, code) { ... }
```

I assume your general problem is that you have an unbounded number of paths
by including object ids in them (like /users/1234/comments). The
path/endpoint is one of the most important labels on these HTTP metrics in
my experience, as it helps to understand which part of your system
misbehaves. Instead of dropping that label altogether, I'd adjust normalize
the paths instead in the label builder. Something like `path:
env['PATH'].gsub(/\/\d+\//, '/:id/')` could work already, but depending on
your paths you might need to write a more sophisticated sanitizer.

**Comment by gaynetdinov** [comment]
Thank you for the great explanation!

**Comment by RichiH** [comment]
For future reference if ever needed: https://github.com/prometheus/client_ruby/pull/57
